import Head from 'next/head'
import Layout from "./../components/Layout";
import Hireme from "./../components/Hireme";
import Image from 'next/image';
import profileImage from "../../public/images/profile/developer-pic-1.png"
import AnimatedText from '@/components/AnimatedText';
import Link from 'next/link';
import { LinkArrow } from '@/components/Icons';
import lightbulb from "../../public/images/svgs/miscellaneous_icons_1.svg"
import TransitionEffect from '@/components/TransitionEffect';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        
      </Head>
      <TransitionEffect />
      <main className='dark:text-light flex justify-center items-center text-dark w-full min-h-screen'>
      <Layout className='pt-0 md:mt-16 sm:mt-8'>
        <div className='flex items-center justify-between w-full lg:flex-col'>
          <div className='w-1/2 md:w-full'>
            <Image
            priority
            sizes='(max-width:768px) 100vw,(max-width:1200px) 50vw,50vw'
            src={profileImage} alt='Umairfarooq' className=' w-full h-auto lg:hidden md:inline-block md:w-full' />
          </div>
        <div className='w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center'>
          <AnimatedText 
          text="Turning Vision Into Reality With Code And Design." className='!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl'
          />
          <p className='my-4 text-base font-medium lg:text-base md:text-sm sm:text-xs'>
          As a skilled full-stack developer, I am dedicated to turning ideas into innovative web applications. 
            Explore my latest projects and articles, showcasing my expertise in React.js and web development.
          </p>
          <div className='flex items-center self-start mt-2 lg:self-center sm:flex-col'>
            <Link href="./dummy.pdf"  className=' dark:bg-light dark:text-dark flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light md:p-2 md:px-4 md:text-base
            ' 
            download={true}
            >Resume <LinkArrow className={"w-6 ml-1  "}/></Link>
            <Link href="mailto:mrumair775@gmail.com" target={'_blank'} className='dark:text-light ml-4 sm:ml-0 sm:mt-2 text-lg font-medium capitalize text-dark hover:underline hover:font-bold md:text-base'>Contact</Link>
          </div>
        </div>
        </div>
      </Layout>
      <Hireme />
      <div className=' absolute right-8 bottom-8 inline-block w-24 XL:w-20 lg:w-18 md:w-16 sm:w-14 hover:scale-150 md:hidden'>
        <Image src={lightbulb} alt='Umair' className='w-full h-full'/>
      </div>
      </main>
    </>
  )
}
